#!/bin/bash
cd $HOME/myexpos/spl
echo ".......Exception Handler..........."
./spl spl_progs/exhandler.spl
echo ".......Compiling Interrupts........"
echo "INT6...."
./spl spl_progs/int6.spl
echo "INT7...."
./spl spl_progs/int7.spl
echo "INT8...."
./spl spl_progs/int8.spl
echo "INT9...."
./spl spl_progs/int9.spl
echo "INT10...."
./spl spl_progs/int10.spl
echo "TIMER...."
./spl spl_progs/contextswitchtimer.spl
echo "DISK INTERRUPT...."
./spl spl_progs/intdisk.spl
echo "CONSOLE INTERRUPT...."
./spl spl_progs/intconsole.spl
echo
echo
echo ".........Compiling OS Code.........."
./spl spl_progs/osstartup.spl
echo
echo
echo "........Compiling Modules........."
echo "MOD0...."
./spl spl_progs/mod0.spl
echo "MOD1...."
./spl spl_progs/mod1.spl
echo "MOD2...."
./spl spl_progs/mod2.spl
echo "MOD4...."
./spl spl_progs/mod4.spl
echo "MOD5...."
./spl spl_progs/mod5.spl
echo "MOD7...."
./spl spl_progs/mod7.spl

cd $HOME/myexpos/xfs-interface
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --exhandler ../spl/spl_progs/exhandler.xsm
./xfs-interface load --os ../spl/spl_progs/osstartup.xsm
./xfs-interface load --int=timer ../spl/spl_progs/contextswitchtimer.xsm
./xfs-interface load --int=console ../spl/spl_progs/intconsole.xsm
./xfs-interface load --int=disk ../spl/spl_progs/intdisk.xsm
./xfs-interface load --int=6 ../spl/spl_progs/int6.xsm
./xfs-interface load --int=7 ../spl/spl_progs/int7.xsm
./xfs-interface load --int=8 ../spl/spl_progs/int8.xsm
./xfs-interface load --int=9 ../spl/spl_progs/int9.xsm
./xfs-interface load --int=10 ../spl/spl_progs/int10.xsm
./xfs-interface load --module 0 ../spl/spl_progs/mod0.xsm
./xfs-interface load --module 1 ../spl/spl_progs/mod1.xsm
./xfs-interface load --module 2 ../spl/spl_progs/mod2.xsm
./xfs-interface load --module 4 ../spl/spl_progs/mod4.xsm
./xfs-interface load --module 5 ../spl/spl_progs/mod5.xsm
./xfs-interface load --module 7 ../spl/spl_progs/mod7.xsm
